### ISSUE TITLE
File to import not found or unreadable: node_modules/@felsgorilla/angular6-toaster/toaster

### ISSUE THREAD

**Issue by ziye201810** [FelsGorilla/angular6-toaster#1]
### steps:
Following the readme file, 
1. run npm install @felsgorilla/angular6-toaster
2. and then I added below code in my src/styles.scss 
**@import 'node_modules/@felsgorilla/angular6-toaster/toaster';**

Error message as below:
`Module build failed (from ./node_modules/sass-loader/lib/loader.js):
@import 'node_modules/@felsgorilla/angular6-toaster/toaster';
^
      File to import not found or unreadable: node_modules/@felsgorilla/angular6-toaster/toaster.
      in /Users/ziye.zhang/Documents/MyProjects/my-app/src/styles.scss (line 5, column 1)
`

**My Analysis:**
Seems there is no toaster.css file under folder angular6-toaster.
I have checked my node_modules and it does not exists.

**Comment by CUBITECH** [comment]
Thats right, since Angular 6 .css files are not welcome anymore.
Instead there is a .scss file. Try using following in your style.scss

@import "~@felsgorilla/angular6-toaster/dist/toaster";
